import { PATH_API } from './path';

export const QUERY_KEY = {
  SIGNUP: PATH_API.SIGNUP,
  DUMMY_MEMBER: PATH_API.DUMMY_MEMBER,
  KAKAO: PATH_API.KAKAO,
  KAKAO_VERIFY: PATH_API.KAKAO_VERIFY,
  INOCULATIONS: PATH_API.INOCULATIONS,
};
